### ISSUE TITLE
Script unable to translate a .srt file with so much lines.

### ISSUE THREAD

**Issue by Nbdyleto** [Nbdyleto/translate-yt-captions#2]
`_translate.py`
```python
text = ''
subs = pysrt.open(input_file)
for sub in subs:
      text += sub.text + '\n'
translated_text = translate(text, from_language=source_language, to_language=target_language)
translated_lines = translated_text.split('\n')
print('translated: ', translated_text)
print('translated_lines: ', translated_lines)
```

_translate.py script passing a SRT file with approximately 288 captions. Returns:

```shell
translated:  
translated_lines:  ['']
0   foreign
1   about Vice news remember Vice news
Traceback (most recent call last):
  File "/home/nbdleto/Documents/Personal Projects/AI-spell-video-cc-correction/_translate.py", line 39, in <module>
    translate_srt(input_file, output_file, source_language, target_language)
  File "/home/nbdleto/Documents/Personal Projects/AI-spell-video-cc-correction/_translate.py", line 19, in translate_srt
    sub.text = translated_lines[i]
IndexError: list index out of range


```

That response not occur when the same content has 120 captions. The script works fine.

A probably solution is break the subtitles in chunks and translate them. Then, put that "chunk" translations into the new SRT file properly.

**Comment by 1ce-one** [comment]
Hello, I'd like to work on this issue. Would you be able to upload the .srt files you used to test this module?

**Comment by Nbdyleto** [comment]
Sure. I uploaded the file that are 288 captions in test-files/
I will be grateful for your help.

**Comment by 1ce-one** [comment]
```File "d:\REP\test\translate-yt-captions\_translate.py", line 35, in <module>
    translate_srt(input_file, output_file, source_language, target_language)
  File "d:\REP\test\translate-yt-captions\_translate.py", line 7, in translate_srt
    subs = pysrt.open(input_file)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sleop\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pysrt\srtfile.py", line 151, in open
    source_file, encoding = cls._open_unicode_file(path, claimed_encoding=encoding)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sleop\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pysrt\srtfile.py", line 292, in _open_unicode_file
    encoding = claimed_encoding or cls._detect_encoding(path)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sleop\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pysrt\srtfile.py", line 279, in _detect_encoding
    file_descriptor = open(path, 'rb')
                      ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'files-to-test/tate-first-interview.srt'```

I am getting error, for some reason its not able to open the srt files. I tried running your code without making any modifications.Are there any prerequisites I'm missing except the pysrt and mtranslate? Or is this the first time you are encountering this issue?

**Comment by Nbdyleto** [comment]
#3
